### ISSUE TITLE
Not working on RPi3

### ISSUE THREAD

**Issue by emirotin** [petrosagg/resin-tether#1]
Not sure if it's something that's easy to fix, but just in case, a report from the user:

```
resin-tether is not working at all. Endless restart of the application, log file shows:


12.07.16 17:20:56 [+0800] Restarting application 'registry.resin.io/airgambit/87403295dcd7feb24c7a4d7f5033a6dd8e227ae8'

12.07.16 17:20:58 [+0800] Setting SSID to: ResinAP

12.07.16 17:20:58 [+0800] Setting Passphrase to: 12345678

12.07.16 17:20:58 [+0800] Enabling tethering on wifi

12.07.16 17:20:58 [+0800] Traceback (most recent call last):

12.07.16 17:20:58 [+0800] File "/app/demo.py", line 40, in <module>

12.07.16 17:20:58 [+0800] tech.SetProperty('Tethering', dbus.Boolean(1))

12.07.16 17:20:58 [+0800] File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__

12.07.16 17:20:58 [+0800] **keywords)

12.07.16 17:20:58 [+0800] File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking

12.07.16 17:20:58 [+0800] message, timeout)

12.07.16 17:20:58 [+0800] dbus.exceptions.DBusException: net.connman.Error.NotSupported: Not supported

```

**Comment by sasha42** [comment]
Same issue here. Trying with https://github.com/resin-io/resin-wifi-connect, looks like the maintainer of this project has also contributed to that one. There are two specific branches for RPi3, they move over to a node app, but still looks promising.

**Comment by petrosagg** [comment]
@sasha42 I've done a lot of work recently to make resin-wifi-connect work on rpi3. This branch[1] works fine and we'll merge it soon but some extra testing would be great :)

[1] https://github.com/resin-io/resin-wifi-connect/tree/rpi3-rebased
